### ISSUE TITLE
Configurações de fonte e estilo devem mesmo ser incorporadas no template ?

### ISSUE THREAD

**Issue by a21ns1g4ts** [LeuAlmeida/workstation#1]
Talvez fosse melhor chamar o conteúdo de configuração do vs code em um arquivo não versionado. 
O que você pensa sobre isso ?

**Comment by LeuAlmeida** [comment]
Excelente ideia, ate porque nem todos - necessariamente - querem as mesmas configs.
Acabei de corrigir isso com as configs do VSCode [aqui](https://github.com/LeuAlmeida/ubuntu-workstation/commit/4742ed340b5ae9bf3429350f116ea6a9159589ce). O proximo passo e fazer o mesmo para as configs do ZSH e fontes.

Obrigado pela contribuicao!
