### ISSUE TITLE
Interfaces para plugins

### ISSUE THREAD

**Issue by a21ns1g4ts** [LeuAlmeida/workstation#2]
Eu realmente aprecio o fato de ter um script que automatiza o processo de configuração do ambiente. Se tivermos uma api que possibilite uma pré configuração do processo podemos tornar o uso dessa ideia de automação mais poderosa e extensível. Seria um design parecido com o que o asdf possuí, só que mais genérica. Gerenciar a ordem dos processos também seria muito interessante. Se realmente isso fosse possível eu poderia escrever um plugin que por exemplo instalasse uma determinada ferramenta aproveitando o core do ubuntu-workstation e sua interface. Por exemplo: eu poderia escrever um plugin personalizado pra instalar o git usando variáveis não versionadas. Uma api para configurações de ambiente seria fantástico pois dessa forma poderíamos deixar o processo menos interativo e mais dinâmico então teríamos um preset mais poderoso. O que você pensa sobre isso ?
Eu não sou habituado com a linguagem shel. Então não sei se chegaria sozinho a esse resultado, porém gostaria de saber se essa ideia pode ser mesclada no código. Vai que eu ou alguém consiga um desses dias.

**Comment by LeuAlmeida** [comment]
Cara, eu achei fantástica a ideia. Se você puder nos dar um exemplo ou enviar um PR com a sua sugestão, será muito bem-vindo!
